In [1]:
import pickle
import pandas as pd
import numpy as np
from sklearn.model_selection import learning_curve,train_test_split

In [2]:
model = pickle.load(open("file.pkl", "rb"))

In [3]:
car = pd.read_csv("cars_dataset.csv")

In [21]:
car[car['price'] < 2470]

model  year  price transmission  mileage fuelType    tax   mpg  \
7795          A3  2005   1975       Manual   104000   Petrol  240.0  38.1   
10108         TT  2002   1990       Manual   131925   Petrol  325.0  30.1   
10552         A4  2004   1699       Manual   110000   Diesel  315.0  36.2   
10588         A3  2003   1490    Automatic   101000   Diesel  240.0  44.5   
17952   5 Series  2002   1595    Automatic   115000   Petrol  325.0  28.5   
...          ...   ...    ...          ...      ...      ...    ...   ...   
72258        I10  2009   1695       Manual    84000   Petrol   30.0  56.5   
72259        I10  2008   1495       Manual    94000   Petrol   30.0  56.5   
72280   Santa Fe  2002   1200       Manual    94000   Petrol  325.0  30.4   
72283       Getz  2003   1990    Automatic    51000   Petrol  260.0  37.2   
72347       Getz  2007   1295       Manual    90800   Petrol  125.0  51.4   

       engineSize     Make  
7795          2.0     audi  
10108         1.8     audi  
10552         2.5     audi  
10588         1.9     audi  
17952         2.2      BMW  
...           ...      ...  
72258         1.2  Hyundai  
72259         1.2  Hyundai  
72280         2.4  Hyundai  
72283         1.6  Hyundai  
72347         1.1  Hyundai  

[194 rows x 10 columns]

In [ ]:
#max price = 35650, min price = 2470

In [ ]:
	2020	Semi-Auto	70	Petrol	145.0	21.1	5.2	audi
    2013	Manual	42000	Petrol	20.0	61.4	1.2	Hyundai
    2020	Manual	2000	Diesel	145.0	52.3	1.6	vw
    2018	Manual	9270	Petrol	145.0	60.1	1.0	skoda
    2017	Automatic	28893	Diesel	150.0	68.9	2.0	BMW
    2019	Automatic	2130	Diesel	145.0	42.8	2.2	Hyundai

In [31]:
mileage = 2130
tax = 145.0
mpg =42.8
engineSize = 2.2
year_2012 = 0
year_2013 = 0
year_2014 = 0
year_2015 = 0
year_2016 = 0
year_2017 = 0
year_2018 = 0
year_2019 = 1
year_2020 = 0
transmission_Automatic = 1
transmission_Manual = 0
transmission_Other = 0
transmission_Semi_Auto = 0
fuelType_Diesel = 1
fuelType_Electric = 0
fuelType_Hybrid = 0
fuelType_Other = 0
fuelType_Petrol = 0
Make_BMW = 0
Make_Ford = 0
Make_Hyundai = 1
Make_audi = 0
Make_skoda = 0
Make_toyota = 0
Make_vw = 0

In [32]:
s6 = model.predict([[mileage,tax,mpg,engineSize,year_2012,year_2013,year_2014,year_2015,year_2016,
                    year_2017,year_2018,year_2019,year_2020,transmission_Automatic,transmission_Manual,
                    transmission_Other,transmission_Semi_Auto,fuelType_Diesel,fuelType_Electric,
                    fuelType_Hybrid,fuelType_Other,fuelType_Petrol,Make_BMW,Make_Ford,Make_Hyundai,
                    Make_audi,Make_skoda,Make_toyota,Make_vw]])

In [10]:
s    #expected = 12500

array([14743.28998348])

In [16]:
s1   #expected = 137995

array([13611.97286261])

In [20]:
s2 # expected = 3995

array([11099.89819216])

In [24]:
s3 #expected = 23500

array([14007.94891597])

In [27]:
s4 #expected = 10795

array([12768.65072123])

In [30]:
s5 #expected = 18700

array([14760.57015555])

In [33]:
s6 #expected = 32450

array([14586.39262916])